### PR TITLE
Incorporate referent and frame id changes to ensure id validation

### PR DESCRIPTION
**Pull request by RickBrannan**

### CODE REVIEW

**Comment by jacobwegner** [comment]
(As with #68, I don't see any changes here that would present an issue with deploying new data / consuming data on the frontend, but I don't have any context to "sign off" on the actual data changes 😄 )

**Review by jonathanrobie — APPROVED** [review]
I approve these changes.

**Comment by jacobwegner** [comment]
@RickBrannan I've been fighting some CI/CD gremlins, but your data changes have now been deployed and are visible within the MACULA Browser:

image

image

**Comment by RickBrannan** [comment]
Thank you, @jacobwegner , much appreciated!

**Pull request merged**
