### PR TITLE
Add macula-greek to Clear Engine mapping

### PR DESCRIPTION
**Pull request by jacobwegner**
- Adds `annotations` directory for standoff annotations
- Adds TSV mapping file inspired by https://github.com/Clear-Bible/symphony-team/discussions/217

(I will circle back here and ensure we're updating the process used to create the initial mapping from https://github.com/Clear-Bible/symphony-team/pull/72)

Closes https://github.com/Clear-Bible/macula-greek/issues/40

### CODE REVIEW

**Comment by jacobwegner** [comment]
@jonathanrobie same as https://github.com/Clear-Bible/macula-hebrew/pull/80; I'd like to merge this and create a version using cal ver (`22.10.11`)

**Comment by jonathanrobie** [comment]
@jacobwegner - I'd like to understand how this would relate to our other mappings - NA28, NA27, SBLGNT, etc., and how this directory relates to `https://github.com/Clear-Bible/macula-greek/tree/sources/Clear/mappings/` and `https://github.com/Clear-Bible/macula-greek/tree/sources/Clear/annotations/`

**Comment by jonathanrobie** [comment]
I also see a few likely glitches:

image


image


image


image


image


image

**Comment by jacobwegner** [comment]
I did fix the glitches, but am closing this for now; we will revisit mappings again in the future.

**Pull request closed without merging**
