### PR TITLE
Marble senses

### PR DESCRIPTION
**Pull request by klosoter**
Added MARBLE-senses to both trees.

Format:

```xml
<morph 
    domain="<(full)domainNumber>;<domainName>;<subDomainName (where applicable)|<second/third/... entry (where applicable)>"
    sdbg="<lemma>;<entryCode>;<gloss>, <gloss>, <gloss>|<second/third/... entry (where applicable)>"
/>
```

I couldn't use `:` because some elements already contained them. 
Split by `|` to extract multiple entries (corresponds between domain and sdbg in order). 
Use `;` to split the attribute categories. 

The domainNumber corresponds to the (sub) domain as follows:
- 3 digits: only a (core) domain. Number refers to core domain only.
- 6 digits: both a core domain and a sub-domain. 
   - the first 3 digits refer to the core domain
   - the complete number (6 digits) refers to the sub-domain

I also created a file that contains all data extracted from MARBLE, like this:
```xml
<marble-data>
  <morph 
    marbleId="04000100100002" 
    domain="033005;Communication;Written Language" 
    sdbg="βίβλος;33.38;written statement, certificate, notice, record"
    />
</marble-data>
```

### CODE REVIEW

**Review by ryderwishart — COMMENTED** [review]
I've pushed an update to the lowfat which pulls directly from the nodes trees.

**Comment by klosoter** [comment]
Updated the node trees with:
- New marble attribute names (`Domain` and `SDBG`)
- Only kept the last domain name (subdomain for 6 digits, and domain for 3 digits)

Changed `lowfat-macula-greek.xquery` to find the new domain names and copy them as (`domain` and `sdbg`)

- Repopulated lowfat with said query 
- Using oXygen, which did the trick of indenting attributes on a new line automatically (BaseX didn't work). Thanks @ryderwishart for the suggestion!

Ready for merging

**Comment by jonathanrobie** [comment]
The `gloss` attribute, containing the Berean glosses, seems to have gotten lost.  I think you and Ryder are adding different attributes at the same time, can we make a list of all the attributes that should be there and check them off?

**Comment by klosoter** [comment]
Added them right now

**Comment by klosoter** [comment]
I'll check the attribute list again and start working on a list

**Comment by klosoter** [comment]
The annotations also seem to have gotten lost. I'm adding them again. 

How would we want to represent the attributes `Frame` `Ref` and `SubjRef` in lowfat? Lower-case?

**Comment by ryderwishart** [comment]
I should just add them to the XQuery. And yes, my apologies for overlooking attributes you are adding. If I have a list of attributes and whether they are located on m or Node elements then I can make sure everything is in the lowfat. 

@jonathanrobie, I think part of the confusion for me comes from being unsure what all needs to be in the lowfat trees. For example, the @n/@nodeId on Nodes is not required, you've told me, so I left it out of the lowfat trees. Do we need all of the other attributes pulled in? What will we do with those attributes once they are on the lowfat trees?

That's a slightly more big-picture question, and for now I can just add whatever attributes are missing. We can always remove some later if we deem them unnecessary.

**Pull request merged**
