### PR TITLE
adding word sense data

### PR DESCRIPTION
**Pull request by sethbam9**

### CODE REVIEW

**Comment by sboisen** [comment]
@sethbam9 i have to confess i'm a little lost on these changes. I'm probably not as savvy on reviewing Github PRs as i should be, and definitely don't know the MACULA repos well yet. Can you provide some summary of the changes and what they're doing?
For example, 
* is https://github.com/Clear-Bible/macula-greek/blob/33-word-senses/sources/Clear/wordsense/greek-wordsenses.tsv the main update you're shipping here? 
* I recognize that `macula_greek_word_id` in that file is identify a word in the text. What's the sense number identifying? Do we have documentation on that anywhere? If not, where should it go @jonathanrobie?
* I see a whole bunch of "lowfat" and "node" file deletions: i'm guessing these were temporary files for wrangling the data that are no longer needed?

Sorry to be so clueless: I just don't have the full context here i expect.

**Comment by sethbam9** [comment]
@sboisen, your summary is correct. I meant to link the original issue here: https://github.com/Clear-Bible/symphony-team/issues/190

**Comment by sboisen** [comment]
@sethbam9 Ok, i see how the commits map to the acceptance criteria. 

I'd suggest some minor code changes (but not necessarily requirements) to "test", but these should wait until after SBL
- test/__init__.py has three places where it's looping over desired_filenames: it might be better to encapsulate that, since there will probably be other code that wants to do similar things.
- i don't see the init-level variables like `__tei_files__` actually referenced anywhere. 
- despite the mostly clear method names in "test_sources.py", comments wouldn't hurt. For example, it looks like `test_ref_attr_correct_format` is checking to make sure there's a header row with (only?) two columns, and that their values match the global variables. But i had to piece together the code to figure that out: you'd help future folks like me by actually documenting what's being tested and (especially) _why_. That will also help future test improvers (maybe me) see any gaps.
- I guess "test_tsv.py" is a placeholder for future tests?
- There are several other things in "macula-greek/sources" that I expect we'll also want to test: so maybe we need to name things to make it clear what tests are testing which sources? (it's a complicated repo structure)

These are _really_ nit-picky comments, however, and I'm fine with approving the PR (and i see in some cases you're just doing what Issue #190 suggested, which isn't wrong).
  
 CC @jonathanrobie : i think you have the next action according to [Issue #190](https://github.com/Clear-Bible/symphony-team/issues/190) once you've approved.

**Comment by sethbam9** [comment]
@sboisen solid feedback, thanks. 

I've yet to learn unit testing best practices as I'm quite new to it. Responses in order:
- That's a good idea. The only code I added was related to the wordsense tests, so I don't know what the author had in mind for all the other pieces.
- Referenced in the test files... e.g., `__tei_files__` is imported in `macula-greek/test/test_nestle1904_tei.py`
- Yes, I should have added comments. I'll do that now. 
- `test_tsv.py` is awaiting `macula-greek.tsv` in `main`. This is following the pattern in `macula-hebrew`. I know there's the tsv in one of the Greek branches, but I'm not sure why it hasn't been merged yet. 

Given the goal of eventually testing for the presence of all source data files, would it make sense to have a nested structure in `test`?

Something like:

```
test/
   sources/
      Cherith         
      Clear           
      GrovesCenter    
      MARBLE           
      OpenScriptures  
      door43          
      tanach.us
```

with the relevant python files?

**Comment by sboisen** [comment]
> Given the goal of eventually testing for the presence of all source data files, would it make sense to have a nested structure in test? ...

Yes, having tests that parallel the structure of the sources being tested seems like a good idea @sethbam9.

**Pull request merged**
