### PR TITLE
Adding synonym data

### PR DESCRIPTION
**Pull request by sethbam9**

### CODE REVIEW

**Comment by jonathanrobie** [comment]
Looks good to me.

**Comment by sboisen** [comment]
@sethbam9 this is okay, but given the discussion in [Strong's Numbers - consistent formatting, extended lexicon · Discussion #246 · Clear-Bible/symphony-team](https://github.com/Clear-Bible/symphony-team/discussions/246) I'd suggest you condense this down to just three columns:
- StrongNumberX1 (A/G/H prefix, no zero padding)
- StrongNumberX2 (same deal)
- Distance

It should still be about as easy to filter Strong's IDs by language if somebody wants to. CC @jonathanrobie

**Comment by jonathanrobie** [comment]
I agree.

Jonathan

**Comment by sethbam9** [comment]
@sboisen @jonathanrobie I have updated accordingly and added a new PR. Give a thumbs up and I'll merge.

**Comment by sboisen** [comment]
Data looks good @sethbam9. I'd suggest you update the ReadMe to match, and then 👍🏻 from me.

**Pull request merged**
