### PR TITLE
Use after and remove brackets

### LINKED ISSUE #20: `after` attribute
The [`macula-hebrew` lowfat syntax trees](https://github.com/Clear-Bible/macula-hebrew/tree/main/lowfat) use an attribute called `after` that helps one join `<w>` elements to correctly form graphical words. This is great! In react / jsx it becomes very simple to render graphical words. Example:

```jsx
<span>{w.text}</span>
{w.after && (<span>{w.after}</span>)}
```

If the macula greek lowfat trees also offered an `after` attribute, consuming applications of both hebrew and greek syntax tree could use the same simple rendering algorithm for all text. The usefulness of consistently including this attribute likely stretches beyond web app front ends too.

### LINKED ISSUE #38: @class='cl', @role='cl'
We currently have a top-level node in each sentence that has `role="cl"`, as opposed to `class="cl"` in lower nodes.   This is confusing to many.

```xml
<wg role="cl">
         <wg class="cl" rule="P2CL" cltype="Verbless" xml:id="400010010010082">
```

Some ways we could fix this:

1. Delete the attribute from the topmost node, or
2. Come up with a meaningful attribute name, or
3. Delete the node itself 

I favor #1, just deleting the attribute.

### PR DESCRIPTION
**Pull request by ryderwishart**
Closes #20 
Closes [#38](https://github.com/Clear-Bible/symphony-tree-editor/issues/38)
Closes https://github.com/Clear-Bible/macula-hebrew/issues/24

### CODE REVIEW

**Comment by jonathanrobie** [comment]
I suspect punctuation should be removed from the `@unicode` attribute, no?

**Comment by ryderwishart** [comment]
> I suspect punctuation should be removed from the `@unicode` attribute, no?

Well I don't actually know where that attribute came from, so I figured it should be an upstream fix, at least in the `Nodes` trees, rather than patching it up after the fact in the `lowfat` data, particularly since we don't use the `@unicode` content for anything at this point.

**Comment by jonathanrobie** [comment]
Please merge this as is, without worrying about @unicode, and we can worry about that next.

**Comment by themikejr** [comment]
Is the `after` attribute now doing two things for us? 

1. Provides information a user needs to render sentences made of graphical words (i.e. when to combine word parts and when not to)
2. Provides information a user needs to properly render punctuation in sentences

**Comment by jonathanrobie** [comment]
> Is the `after` attribute now doing two things for us?
> 
>     1. Provides information a user needs to render sentences made of graphical words (i.e. when to combine word parts and when not to)
> 
>     2. Provides information a user needs to properly render punctuation in sentences

The `@after` attribute does #2, rendering punctuation.

For word parts in Hebrew, use the numbering system, which identifies morphs within a graphical word.

**Comment by themikejr** [comment]
> > Is the `after` attribute now doing two things for us?
> > ```
> > 1. Provides information a user needs to render sentences made of graphical words (i.e. when to combine word parts and when not to)
> > 
> > 2. Provides information a user needs to properly render punctuation in sentences
> > ```
> 
> The `@after` attribute does #2, rendering punctuation.
> 
> For word parts in Hebrew, use the numbering system, which identifies morphs within a graphical word.

@jonathanrobie There are currently several instances in hebrew lowfat where the value of `after` is an empty space. I've been using this to create graphical words. Is this going away? Am I misusing it?

**Comment by jonathanrobie** [comment]
> @jonathanrobie There are currently several instances in hebrew lowfat where the value of `after` is an empty space. I've been using this to create graphical words. Is this going away? Am I misusing it?

You can use `@after` for graphical words.  That's not going away.

**Pull request merged**
