### PR TITLE
Clarify ~865 LN annotations with available data

### PR DESCRIPTION
**Pull request by RickBrannan**

### CODE REVIEW

**Review by jonathanrobie — COMMENTED** [review]
I assume TSV/macula-greek-updated.tsv should replace TSV/macula-greek.tsv?

The XML files need to be formatted with Tidy before they should be merged in - whitespace issues.

Except for those two things, I think it makes sense to merge this in, I don't know an easy way to double check the LN references.  Or is there one?

**Comment by ryderwishart** [comment]
By "clarify" does this mean to fill in some of the blanks?

**Comment by RickBrannan** [comment]
@ryderwishart , the changes I made are detailed here: https://docs.google.com/document/d/1u3W6Mmsa1CcpzSVIHBexlvFtKGEdVO_jJ6rTiMlXMYY/edit?usp=sharing // but yes, some of the empties are now not empty. But not all of them.

**Comment by jonathanrobie** [comment]
Looks good - I approve this pull request.

**Comment by RickBrannan** [comment]
As @jonathanrobie approved the PR, I'll be merging it shortly.

**Comment by jacobwegner** [comment]
@RickBrannan: Still same CI/CD issues as last deploy, but these changes have been manually deployed to the API backend / browser:

image

image

**Pull request merged**
