### PR TITLE
Kill footnotes like '{N:001}'

### PR DESCRIPTION
**Pull request by jonathanrobie**
In each directory, I searched for footnote ids like this:

`grep -rl '{N:001}' .`

Then I replaced them with sed (using xargs):

`grep -rl '{N:001}' . | xargs sed -i 's/{N:001}//g'`

I also searched for N:002, but didn't find any.

### CODE REVIEW

**Comment by jcuenod** [comment]
Looks like only `12.[5-9]` include this footnote

**Comment by rdeblois1960** [comment]
Do you have another way to mark footnote callers?

Reinier
________________________________

**Comment by jonathanrobie** [comment]
> Do you have another way to mark footnote callers? Reinier

Should footnote callers be invoked from these attributes?  @RickBrannan ?

**Comment by jonathanrobie** [comment]
> Looks like only `12.[5-9]` include this footnote

Yes, I think that's right.

**Comment by RickBrannan** [comment]
> Should footnote callers be invoked from these attributes in the Macula trees and TSVs? @RickBrannan ?

I don't think that Macula trees/TSVs should include the callers to the notes.

**Review by RickBrannan — APPROVED** [review]
I agree that removing the `{N:\d+}` notation is appropriate for inclusion of the data in Macula. The lexicon itself should include and utilize such data, but I don't think it necessary for Macula.

**Pull request merged**
