### PR TITLE
WIP: Track changes from branches/jonathan to branches/main

### PR DESCRIPTION
**Pull request by jacobwegner**

### CODE REVIEW

**Comment by jacobwegner** [comment]
https://github.com/Clear-Bible/symphony-backend/pull/69/commits/d503b5edab27ad50534c7cbef27e0382c56eadde has this branch as of https://github.com/Clear-Bible/macula-greek/commit/6af5cff64095dd580d713283a823fe39decc43ff and is being served via a backend deployed to https://deploy-preview-69---symphony-api-dev-25c5xl4maa-uk.a.run.app/symphony-dev/api/wadl

**Comment by jacobwegner** [comment]
I'll get the latest deployed shortly.

**Comment by jacobwegner** [comment]
Latest has been deployed to https://deploy-preview-69---symphony-api-dev-25c5xl4maa-uk.a.run.app/symphony-dev/api/wadl

**Comment by jacobwegner** [comment]
@jonathanrobie 1e69248 has been deployed via https://github.com/Clear-Bible/symphony-backend/pull/69/commits/6d697b1ec3c8c8138b6b3b01f186b66105e3547b

**Comment by jacobwegner** [comment]
@jonathanrobie: Related to https://github.com/Clear-Bible/symphony-team/discussions/128, I've deployed this branch as of 8faa28e111f1662fa9d2d9399fbe9bfc1e4fbceb (via https://github.com/Clear-Bible/symphony-backend/commit/fa9872b76ff4067a551223b7582f0f102ad93f1f) and its contents can be consumed via the following URLs:

https://deploy-preview-69---symphony-api-dev-25c5xl4maa-uk.a.run.app/symphony-dev/api/GNT/Nestle1904/lowfat?usfm-ref=JHN%201:1
https://deploy-preview-jonathan--doric-symphony-preview.netlify.app/
https://deploy-preview-80--symphony-tree-editor-dev.netlify.app/

**Comment by jacobwegner** [comment]
e2516ff has been deployed to the usual places:

https://deploy-preview-69---symphony-api-dev-25c5xl4maa-uk.a.run.app/symphony-dev/api/GNT/Nestle1904/lowfat?usfm-ref=JHN%201:1
https://deploy-preview-jonathan--doric-symphony-preview.netlify.app/
https://deploy-preview-80--symphony-tree-editor-dev.netlify.app/

**Comment by jacobwegner** [comment]
@jonathanrobie 861660f77eb244a7979d02fd1e6869cdeae2a379 has been deployed

**Comment by jacobwegner** [comment]
@jonathanrobie 0cd714d has been deployed (and the style changes synchronzied to https://deploy-preview-109--doric-symphony-preview.netlify.app/):

image

**Comment by jacobwegner** [comment]
@jonathanrobie fec1581 has been deployed

**Comment by jacobwegner** [comment]
5efbd23 has been deployed

**Comment by jacobwegner** [comment]
@jonathanrobie 5efbd23 has been deployed

**Comment by jonathanrobie** [comment]
Could you please merge this again, @jacobwegner ?  I have pushed new changes.

**Comment by jacobwegner** [comment]
d2a7fc8 has been deployed

**Comment by jacobwegner** [comment]
@jonathanrobie 7a6604e60a2bdde14feece5aae81bdd281f46d4d has been deployed

**Comment by jacobwegner** [comment]
@jonathanrobie 7599271321b6f9cb124acbde9f8b653e7115203b has been deployed

**Comment by jacobwegner** [comment]
@jonathanrobie 5b98c854448d4427a797b26cc9446756e531ab39 has been deployed

**Comment by jacobwegner** [comment]
@jonathanrobie f2db7da has been deployed

**Review by jonathanrobie — COMMENTED** [review]
@ryderwishart has improved my css stylesheets and is merging them into the `jonathan` branch.  I suggest we wait until he has done that, then merge.

**Comment by ryderwishart** [comment]
> @ryderwishart has improved my css stylesheets and is merging them into the `jonathan` branch. I suggest we wait until he has done that, then merge.

Update: CSS updates have been merged. https://github.com/Clear-Bible/macula-greek/commit/0e10e26bf8b020ae136c477e044d112404e6c2a8

**Comment by jacobwegner** [comment]
@jonathanrobie https://github.com/Clear-Bible/macula-greek/commit/c950a8dd1ef28a431f414cf875dc010fba35499b has been deployed

**Comment by jacobwegner** [comment]
@ryderwishart d77761cf2a13e7a80664114e5675e0d28fdc29e7 has been deployed

**Comment by jacobwegner** [comment]
0fa5c6c has been deployed

**Comment by jacobwegner** [comment]
[b99f61d](https://github.com/Clear-Bible/macula-greek/pull/39/commits/b99f61dfbe7460bf1b6ffcba07a8280ffcc47d80) has been deployed

**Pull request merged**
